### ISSUE TITLE
ImportError: No module named 'ftputil'

### ISSUE THREAD

**Issue by sabahzero** [mwang87/q2_metabolomicsgnps#43]
qiime2 is working great on my mac terminal, but the q2_metabolomicsgnps plug-in is a no go? I've tried uninstalling and then re-installing as well as restarting. Not sure if good to put in a note for directing users to the Issues page when they encounter installation problems?

**Comment by justinjjvanderhooft** [comment]
If you do "pip install ftputils" within the conda environment it will work fine! 🙂 I already made a note of this in the Google doc with the tutorial two weeks ago. If we can add this to the requirements it should run okay.... 🙂

**Comment by sabahzero** [comment]
Aah, thanks for the quick reply Justin! I definitely missed that note.
Just tried it after re-activating qiime in the conda environment. Output:
"Could not find a version that satisfies the requirement ftputils (from versions: )
No matching distribution found for ftputils"
pip is up-to-date. I'm sure I'm doing something wrong here?

**Comment by sabahzero** [comment]
Hah! I just saw your "Add ftputils to requirements file" issue submission from 11 days ago, too. Somehow missed this even though I "read" the Issues looking for this before submitting. That's what I get for trying to do work on a weekend I guess!

**Comment by justinjjvanderhooft** [comment]
No bother! 🙂 There were many comments in the document.... - did some googling - perhaps it is ftputil (without the s) you need - this might depend on the version of Python you have installed in the conda environment? Otherwise I wouldn't know why it can't find a suitable version....

**Comment by justinjjvanderhooft** [comment]
No bother! 🙂 There were many comments in the document.... - did some googling - perhaps it is ftputil (without the s) you need - this might depend on the version of Python you have installed in the conda environment? Otherwise I wouldn't know why it can't find a suitable version....

**Comment by sabahzero** [comment]
This worked!

**Comment by justinjjvanderhooft** [comment]
So for Python 3 "pip install ftputil" it is!

**Comment by mwang87** [comment]
Updated setup.
