### ISSUE TITLE
I encountered an error，can you help me?

### ISSUE THREAD

**Issue by wonitawowowo** [mwang87/q2_metabolomicsgnps#53]
Thanks for your sharing. And I want to run your codes on my computer,under Ubuntu 18.04.2 LTS and Python 3.6.10.
I try your command：
--------------------------------------------------------------
qiime metabolomics import-gnpsnetworkingclustering \
  --p-manifest manifest.csv \
  --p-credentials credentials.json \
  --o-feature-table categorical_ms2
--------------------------------------------------------------
with the data you provide：
--------------------------------------------------------------
wget -m ftp://massive.ucsd.edu/MSV000082820/peak/
wget -m ftp://massive.ucsd.edu/MSV000082820/other/
--------------------------------------------------------------
then get an error say：
--------------------------------------------------------------
Error creating task (user [wonitawowowo], workflow [METABOLOMICS-SNETS-V2]): [Task parameter validation failed due to 1 error:

  Invalid value for 'Filter Spectra from G6 as Blanks Before Networking': null]
Traceback (most recent call last):
  File "/home/wkz/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/q2cli/commands.py", line 333, in __call__
    results = action(**arguments)
  File "<decorator-gen-523>", line 2, in import_gnpsnetworkingclustering
  File "/home/wkz/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/wkz/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/liaoth/data2/wkz/q2_metabolomics/q2_metabolomics/_method.py", line 149, in import_gnpsnetworkingclustering
    raise ValueError('Task Creation at GNPS failed')
ValueError: Task Creation at GNPS failed
-----------------------------------------------------------------
can you tell me where wrong with it？
Thank you .

**Comment by wonitawowowo** [comment]
I add the code in _method.py
__________________________________________________________________________
invokeParameters["FILTER_G6_BLANKS"] = "0"
__________________________________________________________________________
But the same error still appear，what should i do？

**Comment by wonitawowowo** [comment]
I just recently changed the "0" to "1" ,then it successfully. And in gnps web,the parameter of params.xml  still showed "0".

**Comment by mwang87** [comment]
Thank for letting us know. We'll take a look as the versions on GNPS have advanced and we have not kept this plugin in sync. In the mean time, we'd recommend you run the analysis in GNPS and then simply import the task into qiime2, or better yet simply download the qiime2 artifact output by GNPS.

**Comment by wonitawowowo** [comment]
Thanks for your solution
